apiVersion: 1

datasources:
  - name: timescale-pg
    uid: timescale-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: ${GRAFANA_PG_HOST}
    user: ${GRAFANA_PG_USER}
    secureJsonData:
      password: ${GRAFANA_PG_PASSWORD}
    jsonData:
      database: ${GRAFANA_PG_DATABASE}
      sslmode: disable
      postgresVersion: 1800
      timescaledb: true
      connMaxLifetime: 14400
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
